#include "main.h"

/* Peripheral handle generated by CubeMX */
ADC_HandleTypeDef hadc1;

/* Function prototypes */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_ADC1_Init(void);
void Error_Handler(void);


/* =========================================================
   SETTINGS
   ========================================================= */

#define JOYSTICK_CENTER       2048
#define JOYSTICK_DEADZONE      150

#define MIN_STEP_DELAY_MS        2
#define MAX_STEP_DELAY_MS       20


/* =========================================================
   READ JOYSTICK
   ========================================================= */

static uint16_t Joystick_Read(void)
{
    uint16_t value = 0;

    HAL_ADC_Start(&hadc1);

    if (HAL_ADC_PollForConversion(&hadc1, 10) == HAL_OK)
    {
        value = HAL_ADC_GetValue(&hadc1);
    }

    HAL_ADC_Stop(&hadc1);

    return value;
}


/* =========================================================
   GENERATE ONE STEP
   ========================================================= */

static void Stepper_Step(uint32_t delay_ms)
{
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_SET);
    HAL_Delay(1);

    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET);
    HAL_Delay(delay_ms);
}


/* =========================================================
   MAIN
   ========================================================= */

int main(void)
{
    HAL_Init();

    SystemClock_Config();
    MX_GPIO_Init();
    MX_ADC1_Init();


    /* STEP initially LOW */
    HAL_GPIO_WritePin(GPIOB,
                      GPIO_PIN_0,
                      GPIO_PIN_RESET);

    /* Default direction */
    HAL_GPIO_WritePin(GPIOB,
                      GPIO_PIN_1,
                      GPIO_PIN_RESET);

    HAL_Delay(500);


    while (1)
    {
        uint16_t joystick = Joystick_Read();


        /* -------------------------------------------------
           LIMIT SWITCH
           PC0 LOW = PRESSED
           ------------------------------------------------- */

        if (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_0) == GPIO_PIN_RESET)
        {
            HAL_GPIO_WritePin(GPIOB,
                              GPIO_PIN_0,
                              GPIO_PIN_RESET);

            HAL_Delay(10);
            continue;
        }


        /* -------------------------------------------------
           JOYSTICK CENTER = STOP
           ------------------------------------------------- */

        if ((joystick > (JOYSTICK_CENTER - JOYSTICK_DEADZONE)) &&
            (joystick < (JOYSTICK_CENTER + JOYSTICK_DEADZONE)))
        {
            HAL_GPIO_WritePin(GPIOB,
                              GPIO_PIN_0,
                              GPIO_PIN_RESET);

            HAL_Delay(5);
            continue;
        }


        /* -------------------------------------------------
           JOYSTICK LEFT = ANTICLOCKWISE
           ------------------------------------------------- */

        if (joystick < (JOYSTICK_CENTER - JOYSTICK_DEADZONE))
        {
            uint32_t distance =
                (JOYSTICK_CENTER - JOYSTICK_DEADZONE) - joystick;

            uint32_t range =
                JOYSTICK_CENTER - JOYSTICK_DEADZONE;

            uint32_t delay_ms =
                MAX_STEP_DELAY_MS -
                ((distance *
                  (MAX_STEP_DELAY_MS - MIN_STEP_DELAY_MS))
                 / range);

            if (delay_ms < MIN_STEP_DELAY_MS)
            {
                delay_ms = MIN_STEP_DELAY_MS;
            }

            /* Direction */
            HAL_GPIO_WritePin(GPIOB,
                              GPIO_PIN_1,
                              GPIO_PIN_SET);

            Stepper_Step(delay_ms);
        }


        /* -------------------------------------------------
           JOYSTICK RIGHT = CLOCKWISE
           ------------------------------------------------- */

        else
        {
            uint32_t distance =
                joystick - (JOYSTICK_CENTER + JOYSTICK_DEADZONE);

            uint32_t range =
                4095 - (JOYSTICK_CENTER + JOYSTICK_DEADZONE);

            uint32_t delay_ms =
                MAX_STEP_DELAY_MS -
                ((distance *
                  (MAX_STEP_DELAY_MS - MIN_STEP_DELAY_MS))
                 / range);

            if (delay_ms < MIN_STEP_DELAY_MS)
            {
                delay_ms = MIN_STEP_DELAY_MS;
            }

            /* Direction */
            HAL_GPIO_WritePin(GPIOB,
                              GPIO_PIN_1,
                              GPIO_PIN_RESET);

            Stepper_Step(delay_ms);
        }
    }
}


/* =========================================================
   ADC1
   PA0 = ADC1_IN0
   ========================================================= */

static void MX_ADC1_Init(void)
{
    ADC_ChannelConfTypeDef sConfig = {0};

    hadc1.Instance = ADC1;

    hadc1.Init.ClockPrescaler =
        ADC_CLOCK_SYNC_PCLK_DIV4;

    hadc1.Init.Resolution =
        ADC_RESOLUTION_12B;

    hadc1.Init.ScanConvMode =
        DISABLE;

    hadc1.Init.ContinuousConvMode =
        DISABLE;

    hadc1.Init.DiscontinuousConvMode =
        DISABLE;

    hadc1.Init.ExternalTrigConvEdge =
        ADC_EXTERNALTRIGCONVEDGE_NONE;

    hadc1.Init.ExternalTrigConv =
        ADC_SOFTWARE_START;

    hadc1.Init.DataAlign =
        ADC_DATAALIGN_RIGHT;

    hadc1.Init.NbrOfConversion =
        1;

    hadc1.Init.DMAContinuousRequests =
        DISABLE;

    hadc1.Init.EOCSelection =
        ADC_EOC_SINGLE_CONV;


    if (HAL_ADC_Init(&hadc1) != HAL_OK)
    {
        Error_Handler();
    }


    sConfig.Channel = ADC_CHANNEL_0;
    sConfig.Rank = 1;
    sConfig.SamplingTime = ADC_SAMPLETIME_84CYCLES;


    if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK)
    {
        Error_Handler();
    }
}


/* =========================================================
   GPIO
   ========================================================= */

static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};


    /* Enable GPIO clocks */
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();


    /* -----------------------------------------------------
       PB0 = STEP
       PB1 = DIR
       ----------------------------------------------------- */

    HAL_GPIO_WritePin(GPIOB,
                      GPIO_PIN_0 | GPIO_PIN_1,
                      GPIO_PIN_RESET);

    GPIO_InitStruct.Pin =
        GPIO_PIN_0 | GPIO_PIN_1;

    GPIO_InitStruct.Mode =
        GPIO_MODE_OUTPUT_PP;

    GPIO_InitStruct.Pull =
        GPIO_NOPULL;

    GPIO_InitStruct.Speed =
        GPIO_SPEED_FREQ_HIGH;

    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);


    /* -----------------------------------------------------
       PC0 = LIMIT SWITCH
       ----------------------------------------------------- */

    GPIO_InitStruct.Pin =
        GPIO_PIN_0;

    GPIO_InitStruct.Mode =
        GPIO_MODE_INPUT;

    GPIO_InitStruct.Pull =
        GPIO_PULLUP;

    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
}


/* =========================================================
   SYSTEM CLOCK
   ========================================================= */

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    __HAL_RCC_PWR_CLK_ENABLE();

    __HAL_PWR_VOLTAGESCALING_CONFIG(
        PWR_REGULATOR_VOLTAGE_SCALE1
    );


    RCC_OscInitStruct.OscillatorType =
        RCC_OSCILLATORTYPE_HSI;

    RCC_OscInitStruct.HSIState =
        RCC_HSI_ON;

    RCC_OscInitStruct.HSICalibrationValue =
        RCC_HSICALIBRATION_DEFAULT;

    RCC_OscInitStruct.PLL.PLLState =
        RCC_PLL_ON;

    RCC_OscInitStruct.PLL.PLLSource =
        RCC_PLLSOURCE_HSI;

    RCC_OscInitStruct.PLL.PLLM = 16;
    RCC_OscInitStruct.PLL.PLLN = 360;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
    RCC_OscInitStruct.PLL.PLLQ = 7;


    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
    {
        Error_Handler();
    }


    if (HAL_PWREx_EnableOverDrive() != HAL_OK)
    {
        Error_Handler();
    }


    RCC_ClkInitStruct.ClockType =
        RCC_CLOCKTYPE_HCLK |
        RCC_CLOCKTYPE_SYSCLK |
        RCC_CLOCKTYPE_PCLK1 |
        RCC_CLOCKTYPE_PCLK2;

    RCC_ClkInitStruct.SYSCLKSource =
        RCC_SYSCLKSOURCE_PLLCLK;

    RCC_ClkInitStruct.AHBCLKDivider =
        RCC_SYSCLK_DIV1;

    RCC_ClkInitStruct.APB1CLKDivider =
        RCC_HCLK_DIV4;

    RCC_ClkInitStruct.APB2CLKDivider =
        RCC_HCLK_DIV2;


    if (HAL_RCC_ClockConfig(
            &RCC_ClkInitStruct,
            FLASH_LATENCY_5) != HAL_OK)
    {
        Error_Handler();
    }
}


/* =========================================================
   ERROR HANDLER
   ========================================================= */

void Error_Handler(void)
{
    __disable_irq();

    while (1)
    {
    }
}